### ISSUE TITLE
how is the serial port used?

### ISSUE THREAD

**Issue by Quenii** [enjoy-digital/litesata#24]
I've tried to generate a sata core for ultrascale device using script under bench directory.
And there is a serial port in the top module. so what command should I send to the port to let it run?
and what's the baudrate?

**Comment by enjoy-digital** [comment]
Hello @Quenii,

sorry for the delay. You have to open LiteX Server on the serial port: `litex_server --uart --uart-port=/dev/ttyUSBX` (more information at https://github.com/enjoy-digital/litex/wiki/Use-Host-Bridge-to-control-debug-a-SoC) and then can run the `test_bist.py` script.
